; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = 
	adafruit_grandcentral_m4

[env:due]
platform = atmelsam
board = due
framework = arduino
lib_deps = 
	adafruit/Adafruit BusIO@^1.5.0
	https://github.com/prenticedavid/MCUFRIEND_kbv.git
	adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/Adafruit TouchScreen @ ^1.1.3
	adafruit/SdFat - Adafruit Fork@^2.2.3
	symlink://../..

[env:adafruit_grandcentral_m4]
platform = atmelsam
board = adafruit_grandcentral_m4
framework = arduino
lib_deps =
	adafruit/Adafruit BusIO@^1.5.0
	https://github.com/prenticedavid/MCUFRIEND_kbv.git
	adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/Adafruit TouchScreen @ ^1.1.3
	adafruit/SdFat - Adafruit Fork@^2.2.3
	symlink://../..
